#!/bin/bash
# 
# Author: Nikhil Ranjan Nayak
# Web: https://github.com/nikhilnayak98/cdp
# Email: Nikhil-Ranjan.Nayak@warwick.ac.uk
# Description: webserver stripping

../../scripts/strip-image  \
    -i u2185920/csvs2022-web_i \
    -p nginx \
    -f /etc/passwd \
    -f /etc/group \
    -f '/usr/lib64/libnss*' \
    -f /bin/ls \
    -f /bin/cat \
    -f /bin/sh \
    -f /bin/bash \
    -f /bin/mkdir \
    -f /bin/ps \
    -f /var/run \
    -f /var/log/nginx \
    -f /var/log/php-fpm/error.log \
    -f /var/cache/nginx \
    -f /usr/sbin/php-fpm \
    -f /etc/nginx/nginx.conf \
    -f /etc/php-fpm.conf \
    -f /etc/php-fpm.d/*.conf \
    -f /usr/share/nginx/html \
    -f /docker-entrypoint.sh \
    -d Dockerfile \
    -t u2185920/csvs2022-web_i:stripped