#!/bin/bash
# 
# Author: Nikhil Ranjan Nayak
# Web: https://github.com/nikhilnayak98/csvs
# Email: Nikhil-Ranjan.Nayak@warwick.ac.uk
# Description: webserver stripping with docker-slim

# with docker-slim
docker-slim build \
        --target u2185920/csvs2022-web_i \
        --include-path /usr/share/nginx/html/action.php \
        --include-path /etc/nginx/nginx.conf \
        --include-path /etc/php.ini \
        --include-path /etc/php-fpm.d/www.conf \
        --include-path /etc/nginx/conf.d/php-fpm.conf \
        --tag u2185920/csvs2022-web_i:stripped