#!/bin/bash
# 
# Author: Nikhil Ranjan Nayak
# Web: https://github.com/nikhilnayak98/csvs
# Email: Nikhil-Ranjan.Nayak@warwick.ac.uk
# Description: webserver stripping

# with strip-image script
../../scripts/strip-image  \
        -i u2185920/csvs2022-web_i \
        -p nginx \
        -p php \
        -p php-mysqlnd \
        -p php-fpm \
        -p sh \
        -p bash \
        -f /etc/passwd \
        -f /etc/group \
        -f '/lib/*/libnss*' \
        -f '/lib64/libnss*' \
        -f /bin/ls \
        -f /bin/cat \
        -f /bin/sh \
        -f /bin/mkdir \
        -f /bin/ps \
        -f /var/run \
        -f /var/log/nginx \
        -f /var/log/php-fpm \
        -f /var/cache/nginx \
        -f /usr/sbin/php-fpm \
        -f /etc/nginx/nginx.conf \
        -f /etc/php-fpm.conf \
        -f /etc/php-fpm.d/*.conf \
        -f /usr/share/nginx/html \
        -f /docker-entrypoint.sh \
        -d Dockerfile \
        -t u2185920/csvs2022-web_i:stripped

# with docker-slim
docker-slim build \
        --target u2185920/csvs2022-web_i \
        --include-path /usr/share/nginx/html/action.php \
        --tag u2185920/csvs2022-web_i:stripped