#!/bin/bash
# 
# Author: Nikhil Ranjan Nayak
# Web: https://github.com/nikhilnayak98/csvs
# Email: Nikhil-Ranjan.Nayak@warwick.ac.uk
# Description: dbserver stripping

# with strip-image
../../scripts/strip-image  \
        -i u2185920/csvs2022-db_i \
        -p mariadb-server \
        -f /etc/passwd \
        -f /etc/group \
        -f /tmp \
        -f /var/lib/mysql \
        -f /var/lib/mysqld \
        -f /usr/sbin/mysqld \
        -f /run/mysqld \
        -f /var \
        -d Dockerfile \
        -t u2185920/csvs2022-db_i:stripped

# with docker-slim
docker-slim build \
        --target u2185920/csvs2022-db_i \
        --include-path /docker-entrypoint-initdb.d/ \
        --include-path /usr/local/bin/docker-entrypoint.sh \
        --include-path /mysql/mysql.conf.d/mysqld.cnf \
        --include-path /tmp \
        --include-path /var/run \
        --include-path /run/mysqld/ \
        --include-path /etc/mysql/conf.d/ \
        --include-path /etc/passwd \
        --include-path /etc/group \
        --include-path /etc/shadow \
        --include-path /usr/bin/mysql \
        --include-path /usr/bin/mariadb \
        --include-path /usr/bin/mariadb-install-db \
        --include-path /usr/bin/mariadb-tzinfo-to-sql \
        --include-path /usr/bin/mariadb-admin \
        --include-path /usr/bin/my_print_defaults \
        --include-path /usr/bin/resolveip \
        --include-path /usr/share/mysql/ \
        --include-exe /bin/chown \
        --include-exe /bin/sh \
        --include-exe /bin/uname \
        --include-exe /bin/ls \
        --include-exe /bin/sed \
        --include-exe /bin/sleep \
        --include-exe /bin/mkdir \
        --include-exe /bin/grep \
        --include-exe /bin/su \
        --include-exe /bin/groups \
        --include-shell=true \
        --http-probe=false \
        --tag u2185920/csvs2022-db_i:stripped