#!/bin/bash
# 
# Author: Nikhil Ranjan Nayak
# Web: https://github.com/nikhilnayak98/csvs
# Email: Nikhil-Ranjan.Nayak@warwick.ac.uk
# Description: dbserver stripping with docker-slim

# with docker-slim
docker-slim build \
        --target u2185920/csvs2022-db_i \
        --include-path /mysql/mysql.conf.d/mysqld.cnf \
        --include-path /etc/mysql/conf.d/ \
        --include-path /run/mysqld/ \
        --http-probe=false \
        --tag u2185920/csvs2022-db_i:stripped